AWSTemplateFormatVersion: '2010-09-09'

Description: Template for labelspace cognito resources

Parameters:
  StackName:
    Type: String
    Description: Unique name for stack

Resources:
  UserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        UserPoolName: !Sub ${StackName}-user-pool
        AutoVerifiedAttributes: [email]
        EmailConfiguration:
          SourceArn: arn:aws:ses:eu-west-1:315719867778:identity/welcome@labelspace.ai
        AliasAttributes: [email]
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
        Schema:
          - Name: email
            AttributeDataType: String
            Mutable: false
            Required: true
          - Name: organization
            AttributeDataType: String
            Mutable: true
            Required: false

  UserPoolClient:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName: !Sub ${StackName}-client
        GenerateSecret: false
        UserPoolId: !Ref UserPool

Outputs:
  UserPoolId:
    Value: !Ref UserPool
    Export:
      Name: "UserPool::Id"
  UserPoolClientId:
    Value: !Ref UserPoolClient
    Export:
      Name: "UserPoolClient::Id"